"""Regenerate assets/data/ch03-data.js — the data the Chapter 3 demos draw.

    .venv/bin/python tools/ch03_data.py

Sources
  _data-src/Advertising.csv   the book's own download (statlearning.com); it
                              reproduces Tables 3.1, 3.3, 3.4, 3.5 and 3.6
  ISLP load_data('Credit')    section 3.3 (Figures 3.6, 3.7)
  _data-src/Auto.csv          section 3.3 (Figures 3.8, 3.9)
  ISLP load_data('Carseats')  the three-level dummy demo (ties into lab 3.6.7)
"""
from pathlib import Path

import numpy as np
import pandas as pd

from ISLP import load_data

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "assets" / "data" / "ch03-data.js"


def jsarr(values, ndigits=None):
    out = []
    for v in values:
        if isinstance(v, (int, np.integer)):
            out.append(str(int(v)))
        else:
            f = float(v)
            if ndigits is not None:
                f = round(f, ndigits)
            out.append(repr(f))
    return "[" + ",".join(out) + "]"


ad = pd.read_csv(ROOT / "_data-src" / "Advertising.csv", index_col=0)
credit = load_data("Credit")
auto = pd.read_csv(ROOT / "_data-src" / "Auto.csv", na_values=["?"])
auto["horsepower"] = pd.to_numeric(auto["horsepower"])
auto = auto.dropna(subset=["horsepower"])
car = load_data("Carseats")

lines = [
    "/* Generated by tools/ch03_data.py — do not edit by hand.",
    "   CH03_ADV      Advertising: TV / radio / newspaper budgets and sales (200 rows)",
    "   CH03_CREDIT   Credit: balance, income, student, gender and friends (400 rows)",
    "   CH03_AUTO     Auto: mpg and horsepower (392 rows, NA dropped)",
    "   CH03_CARSEATS Carseats: Sales with the three-level ShelveLoc factor",
    "   Every .levels map says what a 0 / 1 / 2 code stands for. */",
    "",
    "window.CH03_ADV = {",
    "  tv: " + jsarr(ad["TV"].to_numpy(float)) + ",",
    "  radio: " + jsarr(ad["radio"].to_numpy(float)) + ",",
    "  newspaper: " + jsarr(ad["newspaper"].to_numpy(float)) + ",",
    "  sales: " + jsarr(ad["sales"].to_numpy(float)) + ",",
    "};",
    "",
    "window.CH03_CREDIT = {",
    "  balance: " + jsarr(credit["Balance"].to_numpy(int)) + ",",
    "  income: " + jsarr(credit["Income"].to_numpy(float), 2) + ",",
    "  age: " + jsarr(credit["Age"].to_numpy(int)) + ",",
    "  cards: " + jsarr(credit["Cards"].to_numpy(int)) + ",",
    "  education: " + jsarr(credit["Education"].to_numpy(int)) + ",",
    "  limit: " + jsarr(credit["Limit"].to_numpy(int)) + ",",
    "  rating: " + jsarr(credit["Rating"].to_numpy(int)) + ",",
    "  student: " + jsarr((credit["Student"] == "Yes").to_numpy(int)) + ",",
    "  gender: " + jsarr((credit["Gender"] == "Female").to_numpy(int)) + ",",
    "  married: " + jsarr((credit["Married"] == "Yes").to_numpy(int)) + ",",
    "  levels: { student: ['No', 'Yes'], gender: ['Male', 'Female'],"
    " married: ['No', 'Yes'] }",
    "};",
    "",
    "window.CH03_AUTO = {",
    "  mpg: " + jsarr(auto["mpg"].to_numpy(float), 1) + ",",
    "  horsepower: " + jsarr(auto["horsepower"].to_numpy(float)) + ",",
    "  cylinders: " + jsarr(auto["cylinders"].to_numpy(int)) + ",",
    "  origin: " + jsarr(auto["origin"].to_numpy(int)) + ",",
    "  year: " + jsarr(auto["year"].to_numpy(int)) + ",",
    "  levels: { origin: ['American', 'European', 'Japanese'] }",
    "};",
    "",
    "window.CH03_CARSEATS = {",
    "  sales: " + jsarr(car["Sales"].to_numpy(float), 2) + ",",
    "  price: " + jsarr(car["Price"].to_numpy(int)) + ",",
    "  income: " + jsarr(car["Income"].to_numpy(int)) + ",",
    "  advertising: " + jsarr(car["Advertising"].to_numpy(int)) + ",",
    "  shelveloc: " + jsarr(car["ShelveLoc"].cat.codes.to_numpy(int)) + ",",
    "  urban: " + jsarr((car["Urban"] == "Yes").to_numpy(int)) + ",",
    "  us: " + jsarr((car["US"] == "Yes").to_numpy(int)) + ",",
    "  levels: { shelveloc: ['Bad', 'Medium', 'Good'], urban: ['No', 'Yes'],"
    " us: ['No', 'Yes'] }",
    "};",
]

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT} ({OUT.stat().st_size / 1024:.0f} KB)")
