"""Regenerate assets/data/ch04-data.js — the Default data used by the
Chapter 4 demos (sections 4.1 and 4.3).

Run:  .venv/bin/python tools/ch04_data.py
"""
from pathlib import Path

import numpy as np

from ISLP import load_data

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "assets" / "data" / "ch04-data.js"

Default = load_data("Default")
balance = np.round(Default["balance"].to_numpy(float), 2)
income = np.round(Default["income"].to_numpy(float), 2)
default = (Default["default"] == "Yes").to_numpy(int)
student = (Default["student"] == "Yes").to_numpy(int)


def jsarr(a):
    return "[" + ",".join(repr(float(x)) if a.dtype.kind == "f" else str(int(x))
                          for x in a) + "]"


lines = [
    "/* Generated by tools/ch04_data.py — do not edit by hand.",
    "   Source: ISLP `Default` data set (10,000 simulated individuals).",
    "   CH04_DEFAULT.balance  monthly credit card balance",
    "   CH04_DEFAULT.income   annual income (thousands of dollars)",
    "   CH04_DEFAULT.default  1 = defaulted this month (333 people)",
    "   CH04_DEFAULT.student  1 = is a student */",
    "window.CH04_DEFAULT = {",
    "  balance: " + jsarr(balance) + ",",
    "  income: " + jsarr(income) + ",",
    "  default: " + jsarr(default) + ",",
    "  student: " + jsarr(student),
    "};",
]
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT} ({OUT.stat().st_size / 1024:.0f} KB), "
      f"n={len(balance)}, defaulters={int(default.sum())}")
