"""Regenerate assets/data/ch05-data.js — the Portfolio data used by the
Chapter 5 demos (section 5.2).

Run:  .venv/bin/python tools/ch05_data.py
"""
from pathlib import Path

import numpy as np

from ISLP import load_data

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "assets" / "data" / "ch05-data.js"

Portfolio = load_data("Portfolio")
X = np.round(Portfolio["X"].to_numpy(float), 3)
Y = np.round(Portfolio["Y"].to_numpy(float), 3)


def jsarr(a):
    return "[" + ",".join(repr(float(x)) for x in a) + "]"


# Executed reference values (the demos recompute these live in the browser):
cov = np.cov(np.column_stack([X, Y]), rowvar=False)
alpha = (cov[1, 1] - cov[0, 1]) / (cov[0, 0] + cov[1, 1] - 2 * cov[0, 1])
rng = np.random.default_rng(0)
first = second = 0.0
for _ in range(1000):
    idx = rng.choice(100, 100, replace=True)
    c = np.cov(np.column_stack([X, Y])[idx], rowvar=False)
    a = (c[1, 1] - c[0, 1]) / (c[0, 0] + c[1, 1] - 2 * c[0, 1])
    first += a
    second += a * a
boot_se = np.sqrt(second / 1000 - (first / 1000) ** 2)

lines = [
    "/* Generated by tools/ch05_data.py — do not edit by hand.",
    "   Source: ISLP `Portfolio` data set (100 simulated returns for two",
    "   investments X and Y).",
    "   CH05_PORTFOLIO.x   100 returns for investment X",
    "   CH05_PORTFOLIO.y   100 returns for investment Y",
    "   Executed checks (Python, this tool): alpha on all 100 rows ="
    f" {alpha:.4f},",
    f"   bootstrap SE(alpha) with numpy default_rng(0), B=1000 = {boot_se:.4f}",
    "   (the lab prints 0.5758 and 0.0912). */",
    "window.CH05_PORTFOLIO = {",
    "  x: " + jsarr(X) + ",",
    "  y: " + jsarr(Y),
    "};",
    "",
]
OUT.write_text("\n".join(lines), encoding="utf-8")
print(f"wrote {OUT.relative_to(ROOT)}  (n={len(X)}, alpha={alpha:.4f}, bootSE={boot_se:.4f})")
